# .env in the same directory as docker-compose.yml

services:
  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # - ES_JAVA_OPTS=-Xmx896m -Xms768m  # Limit Elasticsearch memory usage
    ports:
      - "${ES_DOCKER_PORT_MAP1}"   # Port mapping for Elasticsearch
      - "${ES_DOCKER_PORT_MAP2}"   # Transport port for Elasticsearch
    volumes:
      - es-data:/usr/share/elasticsearch/data

  # Redis service
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "${REDIS_DOCKER_PORT_MAP}"  # Port mapping for Redis
    volumes:
      - redis-data:/data

  # Zookeeper for Kafka
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "${ZOOKEEPER_DOCKER_PORT_MAP}"  # Port mapping for Zookeeper
    volumes:
      - zookeeper-data:/bitnami/zookeeper

  # Kafka service
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_DOCKER_INTERNAL_PORT}   # Internal port for Zookeeper
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_URL_DOCKER}  # Kafka URL
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
      # - KAFKA_HEAP_OPTS=-Xmx896m -Xms768m  # Limit Kafka Java heap size
    ports:
      - "${KAFKA_DOCKER_PORT_MAP}"  # Port mapping for Kafka
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M  # Limit Kafka memory usage
    #     reservations:
    #       memory: 256M

volumes:
  redis-data:
  kafka-data:
  zookeeper-data:
  es-data:
